development:
  server: "http://localhost:9292/faye"
  secret_token: 'secret'
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
qa:
  server: "http://faye.request.to/faye"
  secret_token: 'baatkaromaalik'
  signature_expiration: 86400
production:
  server: "http://faye.request.to/faye"
  secret_token: 'baatkaromaalik'
  signature_expiration: 86400 # one hour
