# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813504d1ef27d302b49a30088df19366dd3053d920a79c954b5a5406cac5dac6b67b9b892103a7dee56d8140794c9033b5a8c19bb6b363b85e7017ca8756bbac
  twitter_app_id: u3HhLquUQnRS1bo6TiTttv7Bf
  twitter_app_secret: OCCqCQwshbV0Mtr8J2k5koP6qUQVQRYqYYD2haVLQquA9g24cz
  twitter_access_token: 14919287-efpZrREzV1bJ88AwaifvV81ZtuEjXckVpnPuqBwjZ
  twitter_access_token_secret: HlnqNkRVirwlUdj58e3Qp0aitKxIne0ebHy4v1350PBjM

test:
  secret_key_base: b17e45fccab43362b51a2fcd9731c22a16505919411ce586692f67f4beeca09a8ee2b7e3dd5045dff0f6ebe116c820c9bed858018b4befa7434862a59e705a4f
  twitter_app_id: u3HhLquUQnRS1bo6TiTttv7Bf
  twitter_app_secret: OCCqCQwshbV0Mtr8J2k5koP6qUQVQRYqYYD2haVLQquA9g24cz
  twitter_access_token: 14919287-efpZrREzV1bJ88AwaifvV81ZtuEjXckVpnPuqBwjZ
  twitter_access_token_secret: HlnqNkRVirwlUdj58e3Qp0aitKxIne0ebHy4v1350PBjM

# Do not keep production secrets in the repository,
# instead read values from the environment.

qa:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app_id: <%= ENV['TWITTER_APP_ID'] %>
  twitter_app_client: <%= ENV['TWITTER_APP_SECRET'] %>
  twitter_access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  twitter_access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app_id: <%= ENV['TWITTER_APP_ID'] %>
  twitter_app_client: <%= ENV['TWITTER_APP_SECRET'] %>
  twitter_access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  twitter_access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>